spring.application.name=artgallery-backend

spring.datasource.url=jdbc:mysql://mysqldb:3306/artgallerydbb
spring.datasource.username=root
spring.datasource.password=ROOT
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=2004
